analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
  errors:
    mixin_inherits_from_not_object: ignore
  exclude:
  - examples/flutter_gallery/**
  - examples/hello_world/**
  - examples/stocks/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
