name: hello_world_browser

environment:
  sdk: '>2.0.0 <=3.0.0'

dependencies:
  hello_world:
    path: "../hello_world"
  flutter2js: any

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: any
  flutter_test: any

dependency_overrides:
  flutter2js:
    path: ../../
  flutter:
    git:
      url: https://github.com/ethanblake4/flutter2js_packages
      path: packages/flutter
  flutter_test:
    git:
      url: https://github.com/ethanblake4/flutter2js_packages
      path: packages/flutter_test
